### ISSUE TITLE
Could you please check if the cities file is up to date?

### ISSUE THREAD

**Issue by agamsol** [eladnava/pikud-haoref-api#13]

**Comment by agamsol** [comment]
May I ask from where do you crawl the data?

**Comment by pushy** [comment]
Hi @agamsol,
The [`cities.js`](https://github.com/eladnava/pikud-haoref-api/blob/master/lib/cities.js) utility scrapes the cities data from 
the HFC website JSON files (in both Hebrew & English):

https://www.oref.org.il/Shared/Ajax/GetCitiesMix.aspx?lang=he
https://www.oref.org.il/Shared/Ajax/GetCitiesMix.aspx?lang=en

**Comment by eladnava** [comment]
Hi @agamsol,
The [`cities.js`](https://github.com/eladnava/pikud-haoref-api/blob/master/lib/cities.js) utility scrapes the cities data from 
the HFC website JSON files (in both Hebrew & English):

https://www.oref.org.il/Shared/Ajax/GetCitiesMix.aspx?lang=he
https://www.oref.org.il/Shared/Ajax/GetCitiesMix.aspx?lang=en

**Comment by agamsol** [comment]
Could you tell me what does `id` represent in the [`alert.json`](https://www.oref.org.il/WarningMessages/alert/alerts.json) provided from Pikud Haoref?

Here is a alert response from about 2 days ago
```json
{
  "id": "133024095050000000",
  "cat": "1",
  "title": "ירי רקטות וטילים",
  "data": [
    "אחוזם"
  ],
  "desc": "היכנסו למרחב המוגן ושהו בו 10 דקות"
}
```

I couldn't find any explanation for any of the ID's although I can assume what they belong to, except for the `id` and `cat`

**Comment by pushy** [comment]
Hi @agamsol,
It is most likely a unique auto-incrementing database identifier which Pikud Haoref's database assigns to every new alert object. You can use it to keep track of whether you've seen the alert before.

**Comment by eladnava** [comment]
Hi @agamsol,
It is most likely a unique auto-incrementing database identifier which Pikud Haoref assigns to every new alert. You can make use of this field to keep track of whether you have seen this alert before, or if it's the first time.

**Comment by agamsol** [comment]
So after the `alert.json` indicates that there is a threat
I need to save the ID and keep checking if it has been changed in `alert.json` 
and if the new Alert's ID does not match the previous ID it indicates a new threat (at a short time since last threat)?

**Comment by eladnava** [comment]
Hi @agamsol,
Correct. If the ID changes for the same areas indicated in `data` it indicates a new alert for those areas.

**Comment by agamsol** [comment]
but when the ID changes it should overwrite the existing cities in the DATA array no?
there is no case where the DATA has been updated and the ID remains the same?

**Comment by eladnava** [comment]
Hi @agamsol,
The ID is different on a per-alert basis. Every element in the `alerts.json` array has a unique ID which you can use to track whether you have processed the individual alert before.

**Comment by agamsol** [comment]
If I wanted to update `citiesArchive.js`, what file do I need to launch in order to generate the latest file?

**Comment by eladnava** [comment]
Hi @agamsol,
I've just updated it 2 days ago, there haven't been any changes since.
However, `example/cities.js` is the file to run.

**Comment by agamsol** [comment]
By any chance, do you know all of the possible values for `title` inside the [`alerts.json`](https://www.oref.org.il/WarningMessages/alert/alerts.json) file?

Quick debug showed this:

![image](https://user-images.githubusercontent.com/43265196/179848911-a6bf1bdc-a5c5-46f8-86cb-375f85ca2b51.png)

although I want to make sure this is what it can provide, for example- I know it can provide `חדירת מחבלים` which doesn't show in the image above

**Comment by eladnava** [comment]
Hi @agamsol,
Sorry, I do not know the full list of possible values for this field.
