### ISSUE TITLE
using

### ISSUE THREAD

**Issue by AvraMx** [eladnava/pikud-haoref-api#16]
איך אני משתמש בזמן שיש להגיע למקלט ובמפה?

**Comment by eladnava** [comment]
היי @AvraMx,
הפרויקט הזה הוא ספריה שמספקת נתונים מפיקוד העורף, בין אם זה רשימת יישובים עם צבע אדום כרגע (`pikudHaoref.getActiveRocketAlertCities`) או קובץ עם [רשימת היישובים הכוללנית עם מיקומם וזמן הכניסה למרחב המוגן](https://github.com/eladnava/pikud-haoref-api/blob/master/citiesArchive.js).

מה שאתה בוחר לעשות עם הנתונים האלו, זה כבר באחריותך לפתח. מטרת הספריה היא לספק את המידע, ולא להציגו. ההצגה/הנגשה נעשית באפליקציית [צבע אדום](https://redalert.me).
