### ISSUE TITLE
Node-Red node example

### ISSUE THREAD

**Issue by ezcell** [eladnava/pikud-haoref-api#2]
Hi! 
I'd love to integrate this API into my home automation hub (using Node-Red) but my coding skills are terrible. 
Can I make a request to add this node to the Node-Red pallette or if anyone uses node-red, a tutorial how to set it up? 
Thank you so much and keep up the great work!

**Comment by eladnava** [comment]
Hi @ezcell,
Unfortunately this is out of the scope of this package. The proper place to ask for help regarding your request would be StackOverflow:
https://stackoverflow.com/

Since this is not an actual issue with `pikud-haoref-api`, I am closing this.
