### ISSUE TITLE
map not working

### ISSUE THREAD

**Issue by AvraMx** [eladnava/pikud-haoref-api#20]
HI, do you know why is the map not working?

**Comment by eladnava** [comment]
Hi @AvraMx,
Are you referring to the map in the [RedAlert Android](https://github.com/eladnava/redalert-android) app that appears when you tap an alert? 

If so, please provide a screenshot of the map activity not working properly.

Thanks!

**Comment by AvraMx** [comment]
No, im talking about the map.html file

**Comment by eladnava** [comment]
Hi @AvraMx,
The `map.html` is provided just to verify the geocoding accuracy (geolocation) of the Israeli cities scraped from the Pikud Haoref website.

It works, you just need to replace the `[]` on this line:
https://github.com/eladnava/pikud-haoref-api/blob/master/html/map.html#L36

With the array inside [`citiesArchive.json`](https://github.com/eladnava/pikud-haoref-api/blob/master/citiesArchive.js), and then refresh the page:

![Screen Shot 2023-04-09 at 2 48 12 PM](https://user-images.githubusercontent.com/4394189/230760827-53224a91-da11-43f7-b751-b22df864fa8e.png)
