### ISSUE TITLE
api cant be run

### ISSUE THREAD

**Issue by LievreAI** [eladnava/pikud-haoref-api#21]
hey @eladnava

![Screenshot 2023-05-10 211545](https://github.com/eladnava/pikud-haoref-api/assets/84988313/a8a01edb-ff10-4e8d-b0a2-570cd6a56dd6)

i cant run the api

**Comment by eladnava** [comment]
Hi @LievreAI,
Apart from installing the `npm` package, you need to write code to import the package into your own Node.js code, and execute the `pikudHaoref.getActiveRocketAlertCities()` method. 

Detailed instructions and code samples are available in the [Usage section of the README](https://github.com/eladnava/pikud-haoref-api#usage).
