### ISSUE TITLE
Working proxy server

### ISSUE THREAD

**Issue by sidan5** [eladnava/pikud-haoref-api#23]
Have any recommendation for a working proxy server to use? Everything I try doesn't work. Thanks!

**Comment by eladnava** [comment]
Hi @sidan5,
I recommend spinning up an AWS EC2 instance in AWS Israel (Tel Aviv) and installing a proxy software such as Squid on it:
https://www.digitalocean.com/community/tutorials/how-to-set-up-squid-proxy-on-ubuntu-22-04
