### ISSUE TITLE
Are you sure it stopped working?

### ISSUE THREAD

**Issue by ofekashery** [eladnava/pikud-haoref-api#3]
It looks like their website is still using this address
![image](https://user-images.githubusercontent.com/16443111/50878785-f4130500-13e0-11e9-882b-d2afb604e996.png)

**Comment by DemonRem** [comment]
They post a mail on mako you can contact them

**Comment by eladnava** [comment]
Hi @DemonRem,
Definitely, I have contacted them multiple times but they completely ignored my emails.

**Comment by DemonRem** [comment]
Well I also mail them I will wait few days and I will update you if I get any answer

**Comment by ofekashery** [comment]
Even the official app doesn't work.
It's just sad.

**Comment by ofekashery** [comment]
@eladnava It looks like the [``AlertsHistory.json``](https://www.oref.org.il/WarningMessages/History/AlertsHistory.json) file doesn't contain any block.

**Comment by DemonRem** [comment]
you mean the official Pikod Haorf? this the own I have , I can delete it then?

**Comment by eladnava** [comment]
Fixed via https://github.com/eladnava/pikud-haoref-api/commit/c67102ca5cec356261746a7eb7adaad51619fa99. App is back up! 👍

**Comment by ofekashery** [comment]
@eladnava does it work with the new areas?

**Comment by eladnava** [comment]
Hi @ofekashery,
Yes, added compatibility with the new city-based alert format in https://github.com/eladnava/redalert-android/commit/6d04b4b447277f99353b2fb47449f22cd74dcda2 and released in `1.0.9.7` to Google Play 🎉
