### ISSUE TITLE
Where do you get the polygons and what ID do their keys correspond to? 

### ISSUE THREAD

**Issue by yalihart** [eladnava/pikud-haoref-api#32]
Hi, working on a project and wondering where you get the polygon information from?

**Comment by eladnava** [comment]
Hi @yalihart,
The polygon data file (`polygons.json`) was extracted from the [Tzofar app](https://play.google.com/store/apps/details?id=com.redalert.tzevaadom&hl=en).

I'm grateful for all the hard work the Tzofar app developers have put in to gather this data.

Please let me know if you have any other questions.
