### ISSUE TITLE
poll issue

### ISSUE THREAD

**Issue by DemonRem** [eladnava/pikud-haoref-api#5]
@eladnava 
i got issue with the poll issue 

Retrieving active rocket alert zones failed:  [Error: Failed to parse HFC JSON:
SyntaxError: Unexpected token ?]

how to fix it?

**Comment by ofekashery** [comment]
Hey,

It doesn't seem to be JSON, maybe that's a Pikud HaOref error.
Could you send here what is the result of calling the Pikud HaOref?

**Comment by DemonRem** [comment]
Dear that solved but how I know that the api running ?

**Comment by DemonRem** [comment]
![Screenshot_20190506-024133_RedAlert](https://user-images.githubusercontent.com/29927382/57201981-a8e0bb80-6fa8-11e9-86f6-699b37ab6008.jpg)
![20190506_024157](https://user-images.githubusercontent.com/29927382/57201986-ad0cd900-6fa8-11e9-9d81-712b0a25b55c.jpg)
From the rebuilded app and url of the mechine with the api

**Comment by ofekashery** [comment]
You should remove the ``lib/alerts.js`` from the URL

**Comment by DemonRem** [comment]
@ofekashery  how do I know the api running?

**Comment by DemonRem** [comment]
Just done it here this is i get 
![Screenshot_20190506-120639_RedAlert](https://user-images.githubusercontent.com/29927382/57216107-8e81fe80-6ff7-11e9-816a-cc15be4ab315.jpg)

**Comment by ofekashery** [comment]
What is that IP address?

**Comment by DemonRem** [comment]
185.241.7.187

**Comment by ofekashery** [comment]
Yes, but what is this address? The API isn't running on it now

**Comment by DemonRem** [comment]
so how do I run it?

**Comment by eladnava** [comment]
@DemonRem As per https://github.com/eladnava/redalert-android/issues/17 we are awaiting Pikud Haoref's response to bring back the app. 

Creating an alternative alerts API for the app won't help as anyway we need to get official approval to continue operations.

**Comment by eladnava** [comment]
@DemonRem As per https://github.com/eladnava/redalert-android/issues/17#issuecomment-487422685 we are awaiting Pikud Haoref's response to bring back the app. 

Creating an alternative alerts API for the app won't help as anyway we need to get official approval to continue operations.

I appreciate your work and intention. 👍

**Comment by eladnava** [comment]
Fixed via https://github.com/eladnava/pikud-haoref-api/commit/c67102ca5cec356261746a7eb7adaad51619fa99. App is back up! 👍

**Comment by eladnava** [comment]
The app is up and running again! 👍
