### ISSUE TITLE
citiesArchive.js is not updated

### ISSUE THREAD

**Issue by Guy293** [eladnava/pikud-haoref-api#6]
Needs updating to the data.

**Comment by eladnava** [comment]
Thanks for reporting @Guy293, anything specific you noticed which was outdated?

**Comment by eladnava** [comment]
I've updated the HFC cities crawler code to comply with their recent changes and updated `citiesArchive.js`. This file will make it into the RedAlert iOS & Android app on next release.
https://github.com/eladnava/pikud-haoref-api/commit/f4152279adba177c502648ecd13e8c780b7e6ae3
