### ISSUE TITLE
האם הsource עדיין עובד?

### ISSUE THREAD

**Issue by natanhell** [eladnava/pikud-haoref-api#9]
היי,
רציתי לפתח אפליקציית צבע אדום אבל הבנתי שכיום זה כבר בלתי אפשרי מאחר וצריך לבקש רשות מפיקוד העורף.
רציתי לדעת האם הsource שיש כאן עדיין עובד והוא עם אישור של פיקוד העורף, או שאפשר להשתמש בו רק לאחר קבלת אישור
תודה!

**Comment by eladnava** [comment]
היי @natanhell,
הפקג׳ הזה עובד ומתוחזק, ואפשר להשתמש בו לצרכים אישיים או לבניית אפליקציית צבע אדום, לאחר קבלת אישור מפיקוד העורף. אפשר להשתמש בו גם ללא קבלת אישור, אבל זה כבר על אחריותך. 😄
